import type { Metadata } from 'next';
import { Fraunces } from 'next/font/google';
import './globals.css';
import { cn } from '@/classname';
import { Navbar } from '@/components/navbar';
import type { PropsWithChildren } from 'react';

const fraunces = Fraunces({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-fraunces',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" dir="ltr">
      <body className={cn(fraunces.variable, 'bg-gray-1 font-fraunces')}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
